### PR TITLE
Team 10

### PR DESCRIPTION
**Pull request by tricil**

### CODE REVIEW

**Comment by russell-ingram** [comment]
Hello @tricil, we are in the process of reviewing and closing/merging the Hackathon projects for future reference/review. As this contains no code, I am going to close this for now. If you would like some more thorough feedback on your project or any more info about the FNDS services, let us know. Thanks for participating!

**Comment by tricil** [comment]
Alright, thank you!

**Comment by russell-ingram** [comment]
@tricil Actually I just realized the issue with your project is that it was probably pushed with a copied folder that already included a git repo. Therefore no code was actually pushed up. If you'd like to fix that, we're happy to help, but if not I'll close the PR.

**Comment by tricil** [comment]
Yeah give me one second to push it back up. Thanks for the opportunities!

**Comment by tricil** [comment]
i broke the history somehow.

**Comment by russell-ingram** [comment]
Yeah if you reinitialized the .git file that probably cleared the commit history but it would at least maintain the files.

**Comment by tricil** [comment]
Yep, files are good the history (and pull request) are hosed.

**Comment by russell-ingram** [comment]
Makes sense, feel free to open up another PR if you like but if not, no worries!

**Pull request closed without merging**
